// <auto-generated />
using Infrastructure.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519073516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Infrastructure.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category_name");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("Category1Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_category1_id");

                    b.Property<int>("Category2Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_category2_id");

                    b.Property<int?>("Category3Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_category3_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.HasKey("Id");

                    b.HasIndex("Category1Id");

                    b.HasIndex("Category2Id");

                    b.HasIndex("Category3Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.ProductEntity", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.CategoryEntity", "Category1")
                        .WithMany()
                        .HasForeignKey("Category1Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Entities.CategoryEntity", "Category2")
                        .WithMany()
                        .HasForeignKey("Category2Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Entities.CategoryEntity", "Category3")
                        .WithMany()
                        .HasForeignKey("Category3Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category1");

                    b.Navigation("Category2");

                    b.Navigation("Category3");
                });
#pragma warning restore 612, 618
        }
    }
}
